### ISSUE TITLE
These dependencies were not found: GSAP Plugins

### ISSUE THREAD

**Issue by manuelhintermayr** [dipscom/nuxt-gsap-plugins#3]
Hey, when I tried to build and run the master (without chaning anything), I get the following error (meaning, that you cannot use external GSAP plugins here):

 ERROR  Failed to compile with 2 errors

These dependencies were not found:

* gsap/umd/Draggable in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/index.vue?vue&type=script&lang=js&
* gsap/umd/TweenMax in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/index.vue?vue&type=script&lang=js&

To install them, you can run: npm install --save gsap/umd/Draggable gsap/umd/TweenMax

**Comment by dipscom** [comment]
Hey, thanks for the heads up. I'll have a look at them later tonight to see if I can reproduce.

May I ask if you are using GSAP V3 with this? Or the old V2?

This repo is a bit outdated as I have not migrated it to the V3 yet. I will keep a branch for the V2 open and update this as soon as I get a chance.

**Comment by manuelhintermayr** [comment]
Hi, I haven't changed anything yet, 
because I'm still new to GSAP and just want a working NUXT+GSAP project to us as a configuration reference.

Perfect 👍

**Comment by jhull** [comment]
Same issue and wondering if this is a GSAP 3 issue...

**Comment by dipscom** [comment]
Hi @jhull the current version of this repo targets GSAP V2. I'm currently upgrading it to GSAP V3 and the latest version of Nuxt as there are some significant changes to both libraries.

**Comment by dipscom** [comment]
~~Here we go, have a look at this branch and let me know if you are still having issues running the latest GSAP and Nuxt together:~~

~~https://github.com/dipscom/nuxt-gsap-plugins/tree/nuxt-manual-install~~

**Comment by dipscom** [comment]
I have now merged the updates into the master branch. This should be resolved now.
